<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DataPribadiSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('data_pribadi')->insert([
            [
                'nik' => '3201010101010001',
                'no_kk_id' => '3210010101010001',
                'hubungan_keluarga_id' => 1,
                'nama' => 'BUDI SANTOSA',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1975-02-15',
                'jenis_kelamin' => 'LAKI-LAKI',
                'golongan_darah' => 'O',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'tanggal_perkawinan' => '1995-06-20',
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 2,
                'pekerjaan_id' => 5,
                'kewarganegaraan' => 'WNI',
                'penyandang_disabilitas' => 0,
                'nama_ayah' => 'SUDARSO',
                'nama_ibu' => 'SRI WAHYUNI',
            ],
            [
                'nik' => '3201010101010002',
                'no_kk_id' => '3210010101010001',
                'hubungan_keluarga_id' => 3,
                'nama' => 'SRI LESTARI',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1978-07-30',
                'jenis_kelamin' => 'PEREMPUAN',
                'golongan_darah' => 'A',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'tanggal_perkawinan' => '1995-06-20',
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 3,
                'pekerjaan_id' => 2,
                'kewarganegaraan' => 'WNI',
                'penyandang_disabilitas' => 0,
                'nama_ayah' => 'SUMARNO',
                'nama_ibu' => 'KARTINI',
            ],
            [
                'nik' => '3201010101010003',
                'no_kk_id' => '3210010101010001',
                'hubungan_keluarga_id' => 4,
                'nama' => 'ANDI SANTOSA',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2002-11-10',
                'jenis_kelamin' => 'LAKI-LAKI',
                'golongan_darah' => 'B',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'tanggal_perkawinan' => null,
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 3,
                'pekerjaan_id' => 3,
                'kewarganegaraan' => 'WNI',
                'penyandang_disabilitas' => 0,
                'nama_ayah' => 'BUDI SANTOSA',
                'nama_ibu' => 'SRI LESTARI',
            ],
            [
                'nik' => '3201010101010004',
                'no_kk_id' => '3210010101010001',
                'hubungan_keluarga_id' => 4,
                'nama' => 'NINA SANTOSA',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2005-03-21',
                'jenis_kelamin' => 'PEREMPUAN',
                'golongan_darah' => 'O',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'tanggal_perkawinan' => null,
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 3,
                'pekerjaan_id' => null,
                'kewarganegaraan' => 'WNI',
                'penyandang_disabilitas' => 0,
                'nama_ayah' => 'BUDI SANTOSA',
                'nama_ibu' => 'SRI LESTARI',
            ],
            [
                'nik' => '3201010101010005',
                'no_kk_id' => '3210010101010001',
                'hubungan_keluarga_id' => 10,
                'nama' => 'SUPARTO',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1950-06-10',
                'jenis_kelamin' => 'LAKI-LAKI',
                'golongan_darah' => 'A',
                'agama_id' => 1,
                'status_perkawinan' => 'Cerai Mati',
                'tanggal_perkawinan' => '1972-01-01',
                'tanggal_perceraian' => '2020-10-01',
                'pendidikan_terakhir_id' => 2,
                'pekerjaan_id' => null,
                'kewarganegaraan' => 'WNI',
                'penyandang_disabilitas' => 0,
                'nama_ayah' => 'NA',
                'nama_ibu' => 'NA',
            ],
            [
                'nik' => '3201010101010006',
                'no_kk_id' => '3210010101010002',
                'hubungan_keluarga_id' => 1,
                'nama' => 'AGUS FIRMANSYAH',
                'tempat_lahir' => 'Cimahi',
                'tanggal_lahir' => '1980-03-01',
                'jenis_kelamin' => 'LAKI-LAKI',
                'golongan_darah' => 'AB',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'tanggal_perkawinan' => '2004-05-12',
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 4,
                'pekerjaan_id' => 1,
                'kewarganegaraan' => 'WNI',
                'penyandang_disabilitas' => 0,
                'nama_ayah' => 'SUTISNA',
                'nama_ibu' => 'RAHMAH',
            ],
            [
                'nik' => '3201010101010007',
                'no_kk_id' => '3210010101010002',
                'hubungan_keluarga_id' => 3,
                'nama' => 'DEWI RAHAYU',
                'tempat_lahir' => 'Cimahi',
                'tanggal_lahir' => '1982-12-09',
                'jenis_kelamin' => 'PEREMPUAN',
                'golongan_darah' => 'O',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'tanggal_perkawinan' => '2004-05-12',
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 3,
                'pekerjaan_id' => 2,
                'kewarganegaraan' => 'WNI',
                'penyandang_disabilitas' => 0,
                'nama_ayah' => 'SUPARMAN',
                'nama_ibu' => 'MURNI',
            ],
            [
                'nik' => '3201010101010008',
                'no_kk_id' => '3210010101010002',
                'hubungan_keluarga_id' => 4,
                'nama' => 'RINA FIRMANSYAH',
                'tempat_lahir' => 'Cimahi',
                'tanggal_lahir' => '2010-08-25',
                'jenis_kelamin' => 'PEREMPUAN',
                'golongan_darah' => 'A',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'tanggal_perkawinan' => null,
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 1,
                'pekerjaan_id' => null,
                'kewarganegaraan' => 'WNI',
                'penyandang_disabilitas' => 0,
                'nama_ayah' => 'AGUS FIRMANSYAH',
                'nama_ibu' => 'DEWI RAHAYU',
            ],
            [
                'nik' => '3201010101010009',
                'no_kk_id' => '3210010101010002',
                'hubungan_keluarga_id' => 4,
                'nama' => 'REZA FIRMANSYAH',
                'tempat_lahir' => 'Cimahi',
                'tanggal_lahir' => '2015-01-14',
                'jenis_kelamin' => 'LAKI-LAKI',
                'golongan_darah' => 'B',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'tanggal_perkawinan' => null,
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 1,
                'pekerjaan_id' => null,
                'kewarganegaraan' => 'WNI',
                'penyandang_disabilitas' => 0,
                'nama_ayah' => 'AGUS FIRMANSYAH',
                'nama_ibu' => 'DEWI RAHAYU',
            ],
            [
                'nik' => '3201010101010010',
                'no_kk_id' => '3210010101010002',
                'hubungan_keluarga_id' => 10,
                'nama' => 'KARMINAH',
                'tempat_lahir' => 'Cimahi',
                'tanggal_lahir' => '1955-02-10',
                'jenis_kelamin' => 'PEREMPUAN',
                'golongan_darah' => 'AB',
                'agama_id' => 1,
                'status_perkawinan' => 'Cerai Hidup',
                'tanggal_perkawinan' => '1975-02-02',
                'tanggal_perceraian' => '2010-12-01',
                'pendidikan_terakhir_id' => 2,
                'pekerjaan_id' => null,
                'kewarganegaraan' => 'WNI',
                'penyandang_disabilitas' => 0,
                'nama_ayah' => 'NA',
                'nama_ibu' => 'NA',
            ],
        ]);
    }
}