<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DataPribadiSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('data_pribadi')->insert([
            // Keluarga 1 (KK: 3210010101010001) - 5 orang
            [
                'nik' => '3201010101010001',
                'no_kk_id' => '3210010101010001',
                'hubungan_keluarga_id' => 1, // Kepala Keluarga
                'nama' => 'BUDI SANTOSA',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1975-02-15',
                'jenis_kelamin' => 'LAKI-LAKI',
                'golongan_darah' => 'O',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'tanggal_perkawinan' => '1995-06-20',
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 2,
                'pekerjaan_id' => 5,
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null,
                'no_kitap' => null,
                'penyandang_disabilitas' => null,
                'nama_ayah' => 'SUDARSO',
                'nama_ibu' => 'SRI WAHYUNI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3201010101010002',
                'no_kk_id' => '3210010101010001',
                'hubungan_keluarga_id' => 3, // Istri
                'nama' => 'SRI LESTARI',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1978-07-30',
                'jenis_kelamin' => 'PEREMPUAN',
                'golongan_darah' => 'A',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'tanggal_perkawinan' => '1995-06-20',
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 3,
                'pekerjaan_id' => 2,
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null,
                'no_kitap' => null,
                'penyandang_disabilitas' => null,
                'nama_ayah' => 'SUMARNO',
                'nama_ibu' => 'KARTINI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3201010101010003',
                'no_kk_id' => '3210010101010001',
                'hubungan_keluarga_id' => 4, // Anak
                'nama' => 'ANDI SANTOSA',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2002-11-10',
                'jenis_kelamin' => 'LAKI-LAKI',
                'golongan_darah' => 'B',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'tanggal_perkawinan' => null,
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 3,
                'pekerjaan_id' => 3,
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null,
                'no_kitap' => null,
                'penyandang_disabilitas' => null,
                'nama_ayah' => 'BUDI SANTOSA',
                'nama_ibu' => 'SRI LESTARI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3201010101010004',
                'no_kk_id' => '3210010101010001',
                'hubungan_keluarga_id' => 4, // Anak
                'nama' => 'NINA SANTOSA',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2005-03-21',
                'jenis_kelamin' => 'PEREMPUAN',
                'golongan_darah' => 'O',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'tanggal_perkawinan' => null,
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 3,
                'pekerjaan_id' => null,
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null,
                'no_kitap' => null,
                'penyandang_disabilitas' => null,
                'nama_ayah' => 'BUDI SANTOSA',
                'nama_ibu' => 'SRI LESTARI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3201010101010005',
                'no_kk_id' => '3210010101010001',
                'hubungan_keluarga_id' => 10, // Orang Tua
                'nama' => 'SUPARTO',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1950-06-10',
                'jenis_kelamin' => 'LAKI-LAKI',
                'golongan_darah' => 'A',
                'agama_id' => 1,
                'status_perkawinan' => 'Cerai Mati',
                'tanggal_perkawinan' => '1972-01-01',
                'tanggal_perceraian' => '2020-10-01',
                'pendidikan_terakhir_id' => 2,
                'pekerjaan_id' => null,
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null,
                'no_kitap' => null,
                'penyandang_disabilitas' => null,
                'nama_ayah' => 'SUTARMO',
                'nama_ibu' => 'SITI AMINAH',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Keluarga 2 (KK: 3210010101010002) - 4 orang
            [
                'nik' => '3201010101010006',
                'no_kk_id' => '3210010101010002',
                'hubungan_keluarga_id' => 1, // Kepala Keluarga
                'nama' => 'AGUS FIRMANSYAH',
                'tempat_lahir' => 'Cimahi',
                'tanggal_lahir' => '1980-03-01',
                'jenis_kelamin' => 'LAKI-LAKI',
                'golongan_darah' => 'AB',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'tanggal_perkawinan' => '2004-05-12',
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 4,
                'pekerjaan_id' => 1,
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null,
                'no_kitap' => null,
                'penyandang_disabilitas' => null,
                'nama_ayah' => 'SUTISNA',
                'nama_ibu' => 'RAHMAH',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3201010101010007',
                'no_kk_id' => '3210010101010002',
                'hubungan_keluarga_id' => 3, // Istri
                'nama' => 'DEWI RAHAYU',
                'tempat_lahir' => 'Cimahi',
                'tanggal_lahir' => '1982-12-09',
                'jenis_kelamin' => 'PEREMPUAN',
                'golongan_darah' => 'O',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'tanggal_perkawinan' => '2004-05-12',
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 3,
                'pekerjaan_id' => 2,
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null,
                'no_kitap' => null,
                'penyandang_disabilitas' => null,
                'nama_ayah' => 'SUPARMAN',
                'nama_ibu' => 'MURNI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3201010101010008',
                'no_kk_id' => '3210010101010002',
                'hubungan_keluarga_id' => 4, // Anak
                'nama' => 'RINA FIRMANSYAH',
                'tempat_lahir' => 'Cimahi',
                'tanggal_lahir' => '2010-08-25',
                'jenis_kelamin' => 'PEREMPUAN',
                'golongan_darah' => 'A',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'tanggal_perkawinan' => null,
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 1,
                'pekerjaan_id' => null,
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null,
                'no_kitap' => null,
                'penyandang_disabilitas' => null,
                'nama_ayah' => 'AGUS FIRMANSYAH',
                'nama_ibu' => 'DEWI RAHAYU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3201010101010009',
                'no_kk_id' => '3210010101010002',
                'hubungan_keluarga_id' => 4, // Anak
                'nama' => 'REZA FIRMANSYAH',
                'tempat_lahir' => 'Cimahi',
                'tanggal_lahir' => '2015-01-14',
                'jenis_kelamin' => 'LAKI-LAKI',
                'golongan_darah' => 'B',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'tanggal_perkawinan' => null,
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 1,
                'pekerjaan_id' => null,
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null,
                'no_kitap' => null,
                'penyandang_disabilitas' => null,
                'nama_ayah' => 'AGUS FIRMANSYAH',
                'nama_ibu' => 'DEWI RAHAYU',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Keluarga 3 (KK: 3210010101010003) - 3 orang
            [
                'nik' => '3201010101010010',
                'no_kk_id' => '3210010101010003',
                'hubungan_keluarga_id' => 1, // Kepala Keluarga
                'nama' => 'RAHMAN HIDAYAT',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1985-09-12',
                'jenis_kelamin' => 'LAKI-LAKI',
                'golongan_darah' => 'B',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'tanggal_perkawinan' => '2010-11-20',
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 4,
                'pekerjaan_id' => 6,
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null,
                'no_kitap' => null,
                'penyandang_disabilitas' => null,
                'nama_ayah' => 'ABDUL KARIM',
                'nama_ibu' => 'FATIMAH',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3201010101010011',
                'no_kk_id' => '3210010101010003',
                'hubungan_keluarga_id' => 3, // Istri
                'nama' => 'SARI NURJANNAH',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1987-04-18',
                'jenis_kelamin' => 'PEREMPUAN',
                'golongan_darah' => 'A',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'tanggal_perkawinan' => '2010-11-20',
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 3,
                'pekerjaan_id' => 7,
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null,
                'no_kitap' => null,
                'penyandang_disabilitas' => null,
                'nama_ayah' => 'DARMAWAN',
                'nama_ibu' => 'NURHASANAH',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3201010101010012',
                'no_kk_id' => '3210010101010003',
                'hubungan_keluarga_id' => 4, // Anak
                'nama' => 'FAHRI HIDAYAT',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2012-07-03',
                'jenis_kelamin' => 'LAKI-LAKI',
                'golongan_darah' => 'O',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'tanggal_perkawinan' => null,
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 1,
                'pekerjaan_id' => null,
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null,
                'no_kitap' => null,
                'penyandang_disabilitas' => null,
                'nama_ayah' => 'RAHMAN HIDAYAT',
                'nama_ibu' => 'SARI NURJANNAH',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Keluarga 4 (KK: 3210010101010004) - 2 orang
            [
                'nik' => '3201010101010013',
                'no_kk_id' => '3210010101010004',
                'hubungan_keluarga_id' => 1, // Kepala Keluarga
                'nama' => 'INDRA PERMANA',
                'tempat_lahir' => 'Sumedang',
                'tanggal_lahir' => '1992-12-25',
                'jenis_kelamin' => 'LAKI-LAKI',
                'golongan_darah' => 'AB',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'tanggal_perkawinan' => null,
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 4,
                'pekerjaan_id' => 8,
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null,
                'no_kitap' => null,
                'penyandang_disabilitas' => null,
                'nama_ayah' => 'ASEP KURNIA',
                'nama_ibu' => 'TINI MARLINA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3201010101010014',
                'no_kk_id' => '3210010101010004',
                'hubungan_keluarga_id' => 9, // Adik
                'nama' => 'LINA PERMANA',
                'tempat_lahir' => 'Sumedang',
                'tanggal_lahir' => '1995-05-14',
                'jenis_kelamin' => 'PEREMPUAN',
                'golongan_darah' => 'B',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'tanggal_perkawinan' => null,
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 3,
                'pekerjaan_id' => 9,
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null,
                'no_kitap' => null,
                'penyandang_disabilitas' => null,
                'nama_ayah' => 'ASEP KURNIA',
                'nama_ibu' => 'TINI MARLINA',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Keluarga 5 (KK: 3210010101010005) - 1 orang
            [
                'nik' => '3201010101010015',
                'no_kk_id' => '3210010101010005',
                'hubungan_keluarga_id' => 1, // Kepala Keluarga
                'nama' => 'WATI SUSANTI',
                'tempat_lahir' => 'Garut',
                'tanggal_lahir' => '1960-08-08',
                'jenis_kelamin' => 'PEREMPUAN',
                'golongan_darah' => 'O',
                'agama_id' => 1,
                'status_perkawinan' => 'Cerai Mati',
                'tanggal_perkawinan' => '1982-03-15',
                'tanggal_perceraian' => '2018-11-22',
                'pendidikan_terakhir_id' => 2,
                'pekerjaan_id' => 10,
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null,
                'no_kitap' => null,
                'penyandang_disabilitas' => 'Tunanetra Ringan',
                'nama_ayah' => 'SAEPUL BAHRI',
                'nama_ibu' => 'RUMINAH',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Keluarga 6 (KK: 3210010101010006) - 2 orang
            [
                'nik' => '3201010101010016',
                'no_kk_id' => '3210010101010006',
                'hubungan_keluarga_id' => 1, // Kepala Keluarga
                'nama' => 'DEDI KURNIAWAN',
                'tempat_lahir' => 'Tasikmalaya',
                'tanggal_lahir' => '1988-01-30',
                'jenis_kelamin' => 'LAKI-LAKI',
                'golongan_darah' => 'A',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'tanggal_perkawinan' => '2015-08-17',
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 3,
                'pekerjaan_id' => 11,
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null,
                'no_kitap' => null,
                'penyandang_disabilitas' => null,
                'nama_ayah' => 'HERMAN SANTOSO',
                'nama_ibu' => 'NUNUNG NURLAELA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3201010101010017',
                'no_kk_id' => '3210010101010006',
                'hubungan_keluarga_id' => 3, // Istri
                'nama' => 'RINA KURNIAWAN',
                'tempat_lahir' => 'Tasikmalaya',
                'tanggal_lahir' => '1990-11-12',
                'jenis_kelamin' => 'PEREMPUAN',
                'golongan_darah' => 'AB',
                'agama_id' => 1,
                'status_perkawinan' => 'Kawin',
                'tanggal_perkawinan' => '2015-08-17',
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 3,
                'pekerjaan_id' => 2,
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null,
                'no_kitap' => null,
                'penyandang_disabilitas' => null,
                'nama_ayah' => 'BAMBANG SURYADI',
                'nama_ibu' => 'IIS KURNIASIH',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Keluarga 7 (KK: 3210010101010007) - 2 orang
            [
                'nik' => '3201010101010018',
                'no_kk_id' => '3210010101010007',
                'hubungan_keluarga_id' => 1, // Kepala Keluarga
                'nama' => 'YUSUF MAHARDHIKA',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '1983-06-06',
                'jenis_kelamin' => 'LAKI-LAKI',
                'golongan_darah' => 'B',
                'agama_id' => 1,
                'status_perkawinan' => 'Cerai Hidup',
                'tanggal_perkawinan' => '2008-02-14',
                'tanggal_perceraian' => '2020-09-10',
                'pendidikan_terakhir_id' => 4,
                'pekerjaan_id' => 12,
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null,
                'no_kitap' => null,
                'penyandang_disabilitas' => null,
                'nama_ayah' => 'MAHMUD YUSUF',
                'nama_ibu' => 'AISYAH MARYAM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3201010101010019',
                'no_kk_id' => '3210010101010007',
                'hubungan_keluarga_id' => 4, // Anak
                'nama' => 'ZAHRA MAHARDHIKA',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2009-10-20',
                'jenis_kelamin' => 'PEREMPUAN',
                'golongan_darah' => 'A',
                'agama_id' => 1,
                'status_perkawinan' => 'Belum Kawin',
                'tanggal_perkawinan' => null,
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 1,
                'pekerjaan_id' => null,
                'kewarganegaraan' => 'WNI',
                'no_paspor' => null,
                'no_kitap' => null,
                'penyandang_disabilitas' => null,
                'nama_ayah' => 'YUSUF MAHARDHIKA',
                'nama_ibu' => 'SITI MARIAM',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Keluarga 8 (KK: 3210010101010008) - 1 orang
            [
                'nik' => '3201010101010020',
                'no_kk_id' => '3210010101010008',
                'hubungan_keluarga_id' => 1, // Kepala Keluarga
                'nama' => 'MARIA CHRISTINA',
                'tempat_lahir' => 'Manado',
                'tanggal_lahir' => '1979-04-25',
                'jenis_kelamin' => 'PEREMPUAN',
                'golongan_darah' => 'O',
                'agama_id' => 2, // Kristen
                'status_perkawinan' => 'Belum Kawin',
                'tanggal_perkawinan' => null,
                'tanggal_perceraian' => null,
                'pendidikan_terakhir_id' => 5,
                'pekerjaan_id' => 13,
                'kewarganegaraan' => 'WNA',
                'no_paspor' => 'X1234567',
                'no_kitap' => 'KTP123456789',
                'penyandang_disabilitas' => null,
                'nama_ayah' => 'ROBERT CHRISTIAN',
                'nama_ibu' => 'HELENA MARIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}