<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PekerjaanSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('pekerjaan')->insert([
            ['id' => 1, 'nama' => 'Belum/Tidak Bekerja'],
            ['id' => 2, 'nama' => 'Mengurus Rumah Tangga'],
            ['id' => 3, 'nama' => 'Pelajar/Mahasiswa'],
            ['id' => 4, 'nama' => 'Pensiunan'],
            ['id' => 5, 'nama' => 'Pegawai Negeri Sipil (PNS)'],
            ['id' => 6, 'nama' => 'Tentara Nasional Indonesia (TNI)'],
            ['id' => 7, 'nama' => 'Kepolisian RI (POLRI)'],
            ['id' => 8, 'nama' => 'Perdagangan'],
            ['id' => 9, 'nama' => 'Petani/Pekebun'],
            ['id' => 10, 'nama' => 'Peternak'],
            ['id' => 11, 'nama' => 'Nelayan/Perikanan'],
            ['id' => 12, 'nama' => 'Industri'],
            ['id' => 13, 'nama' => 'Konstruksi'],
            ['id' => 14, 'nama' => 'Transportasi'],
            ['id' => 15, 'nama' => 'Karyawan Swasta'],
            ['id' => 16, 'nama' => 'Karyawan BUMN'],
            ['id' => 17, 'nama' => 'Karyawan BUMD'],
            ['id' => 18, 'nama' => 'Karyawan Honorer'],
            ['id' => 19, 'nama' => 'Buruh Harian Lepas'],
            ['id' => 20, 'nama' => 'Buruh Tani/Perkebunan'],
            ['id' => 21, 'nama' => 'Buruh Nelayan/Perikanan'],
            ['id' => 22, 'nama' => 'Buruh Peternakan'],
            ['id' => 23, 'nama' => 'Pembantu Rumah Tangga'],
            ['id' => 24, 'nama' => 'Tukang Cukur'],
            ['id' => 25, 'nama' => 'Tukang Listrik'],
            ['id' => 26, 'nama' => 'Tukang Batu'],
            ['id' => 27, 'nama' => 'Tukang Kayu'],
            ['id' => 28, 'nama' => 'Tukang Sol Sepatu'],
            ['id' => 29, 'nama' => 'Tukang Las/Pandai Besi'],
            ['id' => 30, 'nama' => 'Tukang Jahit'],
            ['id' => 31, 'nama' => 'Tukang Gigi'],
            ['id' => 32, 'nama' => 'Penata Rias'],
            ['id' => 33, 'nama' => 'Penata Busana'],
            ['id' => 34, 'nama' => 'Penata Rambut'],
            ['id' => 35, 'nama' => 'Mekanik'],
            ['id' => 36, 'nama' => 'Seniman'],
            ['id' => 37, 'nama' => 'Tabib'],
            ['id' => 38, 'nama' => 'Paraji'],
            ['id' => 39, 'nama' => 'Perancang Busana'],
            ['id' => 40, 'nama' => 'Penterjemah'],
            ['id' => 41, 'nama' => 'Imam Masjid'],
            ['id' => 42, 'nama' => 'Pendeta'],
            ['id' => 43, 'nama' => 'Pastor'],
            ['id' => 44, 'nama' => 'Wartawan'],
            ['id' => 45, 'nama' => 'Ustadz/Mubaligh'],
            ['id' => 46, 'nama' => 'Juru Masak'],
            ['id' => 47, 'nama' => 'Promotor Acara'],
            ['id' => 48, 'nama' => 'Anggota DPR-RI'],
            ['id' => 49, 'nama' => 'Anggota DPD'],
            ['id' => 50, 'nama' => 'Anggota BPK'],
            ['id' => 51, 'nama' => 'Presiden'],
            ['id' => 52, 'nama' => 'Wakil Presiden'],
            ['id' => 53, 'nama' => 'Anggota Mahkamah Konstitusi'],
            ['id' => 54, 'nama' => 'Anggota Kabinet/Kementerian'],
            ['id' => 55, 'nama' => 'Duta Besar'],
            ['id' => 56, 'nama' => 'Gubernur'],
            ['id' => 57, 'nama' => 'Wakil Gubernur'],
            ['id' => 58, 'nama' => 'Bupati'],
            ['id' => 59, 'nama' => 'Wakil Bupati'],
            ['id' => 60, 'nama' => 'Walikota'],
            ['id' => 61, 'nama' => 'Wakil Walikota'],
            ['id' => 62, 'nama' => 'Anggota DPRD Provinsi'],
            ['id' => 63, 'nama' => 'Anggota DPRD Kabupaten/Kota'],
            ['id' => 64, 'nama' => 'Dosen'],
            ['id' => 65, 'nama' => 'Guru'],
            ['id' => 66, 'nama' => 'Pilot'],
            ['id' => 67, 'nama' => 'Pengacara'],
            ['id' => 68, 'nama' => 'Notaris'],
            ['id' => 69, 'nama' => 'Arsitek'],
            ['id' => 70, 'nama' => 'Akuntan'],
            ['id' => 71, 'nama' => 'Konsultan'],
            ['id' => 72, 'nama' => 'Dokter'],
            ['id' => 73, 'nama' => 'Bidan'],
            ['id' => 74, 'nama' => 'Perawat'],
            ['id' => 75, 'nama' => 'Apoteker'],
            ['id' => 76, 'nama' => 'Psikiater/Psikolog'],
            ['id' => 77, 'nama' => 'Penyiar Televisi'],
            ['id' => 78, 'nama' => 'Penyiar Radio'],
            ['id' => 79, 'nama' => 'Pelaut'],
            ['id' => 80, 'nama' => 'Peneliti'],
            ['id' => 81, 'nama' => 'Sopir'],
            ['id' => 82, 'nama' => 'Pialang'],
            ['id' => 83, 'nama' => 'Paranormal'],
            ['id' => 84, 'nama' => 'Pedagang'],
            ['id' => 85, 'nama' => 'Perangkat Desa'],
            ['id' => 86, 'nama' => 'Kepala Desa'],
            ['id' => 87, 'nama' => 'Biarawati'],
            ['id' => 88, 'nama' => 'Wiraswasta'],
            ['id' => 89, 'nama' => 'Lainnya'],
            ['id' => 90, 'nama' => 'Programmer'],
            ['id' => 91, 'nama' => 'Desainer Grafis'],
            ['id' => 92, 'nama' => 'Youtuber'],
            ['id' => 93, 'nama' => 'Content Creator'],
            ['id' => 94, 'nama' => 'Influencer'],
            ['id' => 95, 'nama' => 'Streamer'],
            ['id' => 96, 'nama' => 'Barista'],
            ['id' => 97, 'nama' => 'Customer Service'],
            ['id' => 98, 'nama' => 'Digital Marketing'],
            ['id' => 99, 'nama' => 'Data Analyst'],
        ]);
    }
}